language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -r requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors
script:
    - coverage run --source="." manage.py test some_app other_app --settings=test_project.settings.test_settings
after_success:
    - coveralls
